package fr.upem.chathack.common.model;

public enum OpCode {
  ANONYMOUS_CLIENT_CONNECTION, //
  AUTHENTICATED_CLIENT_CONNECTION, //
  BROADCAST_MESSAGE, //
  REQUEST_PRIVATE_CLIENT_CONNECTION, //
  SERVER_NOTIFY_PRIVATE_CLIENT_CONNECTION, //
  CLIENT_FAILED_PRIVATE_CLIENT_CONNECTION, //
  SUCCEDED_PRIVATE_CLIENT_CONNECTION, //
  PRIVATE_MESSAGE,
}   